### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by bananabr** [JackOfMostTrades/gadgetinspector#10]
When running the tool against a set of jar files, the following errors are thrown when using Java 11.0.14 (Zulu). The same doesn't happen when using Java 8.

```2022-03-10 18:21:12,637 gadgetinspector.CallGraphDiscovery [ERROR] Error analyzing: gadgetinspector/PassthroughDiscovery$PassthroughDataflowMethodVisitor.class
java.lang.UnsupportedOperationException
	at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at gadgetinspector.CallGraphDiscovery.discover(CallGraphDiscovery.java:35)
	at gadgetinspector.GadgetInspector.main(GadgetInspector.java:110)
2022-03-10 18:21:12,637 gadgetinspector.CallGraphDiscovery [ERROR] Error analyzing: gadgetinspector/Util$1.class
java.lang.UnsupportedOperationException
	at org.objectweb.asm.ClassVisitor.visitNestHostExperimental(ClassVisitor.java:158)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at gadgetinspector.CallGraphDiscovery.discover(CallGraphDiscovery.java:35)
	at gadgetinspector.GadgetInspector.main(GadgetInspector.java:110)
2022-03-10 18:21:12,638 gadgetinspector.CallGraphDiscovery [ERROR] Error analyzing: gadgetinspector/Util.class
java.lang.UnsupportedOperationException
	at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at gadgetinspector.CallGraphDiscovery.discover(CallGraphDiscovery.java:35)
	at gadgetinspector.GadgetInspector.main(GadgetInspector.java:110)
```

**Comment by sig1nt** [comment]
Hey @bananabr, this repo seems pretty unmaintained. I'm keeping an up to date version at https://github.com/sig1nt/gadgetinspector if you want to check it out.
